wandb_version: 1

model:
  desc: null
  value: featurewiz + XGBoost
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.14.2
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1681840912.176396
    t:
      1:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.14.2
      8:
      - 1
      - 2
      - 3
      - 5
